services:
  # Настройка основного приложения (Spring Boot)
  - type: web
    name: video-chatting
    runtime: docker # Указываем Docker вместо node
    plan: free
    region: frankfurt # Или любой другой регион, близкий к вам
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromService:
          type: postgres
          name: video-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromService:
          type: postgres
          name: video-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromService:
          type: postgres
          name: video-db
          property: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update # Автоматически создаст таблицы при первом запуске

  # Настройка базы данных
  - type: postgres
    name: video-db
    region: frankfurt
    plan: free
    databaseName: video_chat_db
    user: admin_user