spring.application.name=video-chatting
server.port=8080

spring.datasource.url=jdbc:postgresql://192.168.1.7:5432/db
spring.datasource.username=postgres
spring.datasource.password=Sardorbek.01

jitsi.meet.url=https://meet.jit.si/
app.id=myApp

ws.secret=NMR7p4LAmbK+MdcYhqTzxnmcuUx8gY5qJ4kSamYHNdo
ws.expiration=86400000