spring.application.name=video-chatting
server.port=8080


#spring.datasource.url=${DATABASE_URL:${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:fly-db}}}
#spring.datasource.username=${DB_USER:${SPRING_DATASOURCE_USERNAME:postgres}}
#spring.datasource.password=${DB_PASS:${SPRING_DATASOURCE_PASSWORD:postgres}}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-d7au0a4hg0os73a3lq20-a/db_4r6x
spring.datasource.username=db_4r6x_user
spring.datasource.password=1Xn5gEmtCGrEEhzPHsMuYzs5fUfW0mat


# Connection Pool Settings
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.leak-detection-threshold=60000
spring.datasource.hikari.connection-test-query=SELECT 1

#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.connection.provider_disables_autocommit=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.format_sql=true

spring.transaction.default-timeout=30
spring.jpa.properties.hibernate.transaction.coordinator_class=jdbc

spring.web.cors.allowed-origins=http://localhost:3001
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true

# Show what Hibernate is doing (useful for debugging)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

jitsi.meet.url=https://meet.jit.si/
app.id=myApp

ws.secret=NMR7p4LAmbK+MdcYhqTzxnmcuUx8gY5qJ4kSamYHNdo
ws.expiration=86400000